### PR TITLE
chore: remove package-lock.json

### PR DESCRIPTION
**Pull request by itsmegrave**
https://github.com/SwachhApp/Swachh/issues/9

### CODE REVIEW

**Comment by sandipbhuyan** [comment]
@meetcric remove package lock from other files too

**Comment by itsmegrave** [comment]
> @meetcric remove package lock from other files too

from where?

**Comment by sandipbhuyan** [comment]
Swachh client and swachh admin repo

**Comment by sandipbhuyan** [comment]
I am merging the pull request for this project. will work on other projects soon

**Pull request merged**
